### ISSUE TITLE
broken subdivision

### ISSUE THREAD

**Issue by samhodge** [JannerM/intrinsics-network#1]
I was trying to reproduce your sample set with:

http://shapenet.cs.stanford.edu/shapenet/obj-zip/ShapeNetCore.v1/03790512.zip

the objects don't subdivide well with Version 2.79 (2.79 2017-09-11, Blender ) on OSX.

I could pre process the models in meshlab, but I was wondering what your solution was.

**Comment by samhodge** [comment]
It seems on further inspection the normals of these models are fairly broken.

**Comment by jannerm** [comment]
Yeah, the normals in most of the ShapeNet models are very strange. Subdivision seemed to fix this issue (at least to the extent that I could make images like those shown [here](https://github.com/JannerM/intrinsics-network/tree/master/git/shapenet)) for all of the categories I looked at though. Which ones were giving you trouble? (Could you attach a rendered image?)

**Comment by samhodge** [comment]
Sorry for the late reply it was the motorbikes as I remember.
