### ISSUE TITLE
For normal .obj files rendering

### ISSUE THREAD

**Issue by Alvin0629** [JannerM/intrinsics-network#13]
hi dear Michael,

I am using your rendering code to render intrinsic images from normal .obj dataset like faces. The raw files (.obj and .mtl, .png) are in the attached zip file. I found for common obj mesh, they do not have many "Mesh" groups like in ShapeNet. So for ShapeNet, I can render intrinsic images without problems, but for normal obj files, I cannot load the color/texture in composite/albedo with your code. The rendered result is here:  
Composite:
![image](https://user-images.githubusercontent.com/67607611/93841515-d55eab80-fc61-11ea-8469-c4a96e97af65.png) 
Albedo: 
![image](https://user-images.githubusercontent.com/67607611/93841543-eb6c6c00-fc61-11ea-8865-38d7f8877f37.png)
Depth:
![image](https://user-images.githubusercontent.com/67607611/93841551-f1fae380-fc61-11ea-8899-5a61ddad1531.png)

Could you please help to check or have some suggestions on how to modify your codes to make it also worked for normal obj files? Thanks sooo much!!!

[0365489.zip](https://github.com/JannerM/intrinsics-network/files/5259053/0365489.zip)

**Comment by jannerm** [comment]
This dataset preparation code is pretty tailored to ShapeNet, but I actually have code in another repo specifically for rendering intrinsic images of face meshes like these: https://github.com/JannerM/face-intrinsics.

Hope this is useful!

**Comment by Alvin0629** [comment]
> This dataset preparation code is pretty tailored to ShapeNet, but I actually have code in another repo specifically for rendering intrinsic images of face meshes like these: https://github.com/JannerM/face-intrinsics.
> 
> Hope this is useful!

Thanks Michael! I will try this repo to see and let you know.
