### ISSUE TITLE
Error downloading datasets 

### ISSUE THREAD

**Issue by MalihaUCF** [JannerM/intrinsics-network#9]
The links in download_dataset.sh seem to be broken. I get this error

<img width="554" alt="screen shot 2018-11-04 at 1 36 48 pm" src="https://user-images.githubusercontent.com/42460909/47968351-d1f2b480-e036-11e8-8e4c-381747887fab.png">

Can you please update the links?  I am downloading just one dataset hence using this command

./download_data.sh {car}

Thank you

**Comment by jannerm** [comment]
Try without the curly braces:
```
./download_data.sh car
```

**Comment by MalihaUCF** [comment]
Thank you, it worked! :) I was hoping to find a big number of RGB images per model in cars category though.
